POST http://localhost:3000/api/invoices
Content-Type: application/json

{
  "id": "000 001",
  "date": "2021-06-18",
  "me": {
    "name": "Mazeika LLC",
    "description": "Software Engineering Services",
    "address": "123 Main St\nBoston, MA 02115"
  },
  "client": {
    "name": "My Client",
    "address": "321 Second St\nNew York, NY 10001",
    "currency": "gbp"
  },
  "lineItems": [],
  "billing": {
    "increment": 15,
    "net": 30,
    "currency": "usd"
  },
  "bank": [
    {
      "key": "Account Holder",
      "value": "John Doe"
    },
    {
      "key": "Routing #",
      "value": "123456789"
    },
    {
      "key": "Account #",
      "value": "987654321"
    }
  ],
  "template": "<p>{{me.description}}</p>"
}

###
